# Generated by Django 5.2.1 on 2025-05-09 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_officer_groups_officer_is_active_officer_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
    ]
