# Generated by Django 5.2.1 on 2025-05-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_candidate_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
    ]
