# Generated by Django 5.2.1 on 2025-05-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_remove_vote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='fingerprint_format',
            field=models.CharField(choices=[('ANSI', 'ANSI'), ('ISO', 'ISO')], default='ANSI', max_length=10),
        ),
    ]
