# Generated by Django 5.2.1 on 2025-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_voter_created_at_voter_fingerprint_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='fingerprint_format',
        ),
        migrations.AlterField(
            model_name='voter',
            name='fingerprint_template',
            field=models.TextField(),
        ),
    ]
